---
all:
  hosts:
    el-instance:
    ki-instance:
elasticsearch:
  hosts:
    el-instance:
        ansible_host: some_IP
  vars:
    ansible_connection: ssh
    ansible_user: someuser
kibana:
  hosts:
    ki-instance:
        ansible_host: some_IP
  vars:
    ansible_connection: ssh
    ansible_user: someuser
filebeat:
  hosts:
    el-instance:
    ki-instance:
