{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "(process_cpu_seconds_total{})" }
   ]
  },
  {
   "title": "CPULA 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(process_cpu_seconds_total{job=\"host\"}[1m])*1000)"
    }
   ]
  },
  {
   "title": "CPULA 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(process_cpu_seconds_total{job=\"host\"}[5m])*1000)"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=\"172.27.116.110:9100\",job=\"host\"}[1m]) + avg_over_time(node_memory_Cached_bytes{instance=\"172.27.116.110:9100\",job=\"host\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{instance=\"172.27.116.110:9100\",job=\"host\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{instance=\"172.27.116.110:9100\",job=\"host\"}[1m])))"
    }
   ]
  },
  {
   "title": "CPULA 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(process_cpu_seconds_total{job=\"host\"}[15m])*1000)"
    }
   ]
  },
  {
   "title": "Free space %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"host\"}*100/node_filesystem_size_bytes{job=\"host\"}"
    }
   ]
  }
 ]
}