kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kube-saas:list-and-logs
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "describe"]
---

apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  name: read-pods-logs
  namespace: default
subjects:
- kind: User
  name: log-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: kube-saas:list-and-logs
  apiGroup: rbac.authorization.k8s.io
