version: '3.1'

services:

  db:
    image: postgres:12
    volumes:
      - ./docker-volume/pgdata:/var/lib/postgresql/data/pgdata
      - ./docker-volume/backup:/backup
    restart: always
    environment:
      POSTGRES_PASSWORD: SomePassw0rd
      POSTGRES_DB: 06-db-02-sql
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080